# Generated by Django 4.0.2 on 2022-03-09 11:14

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Comics url')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('preview_image', models.ImageField(upload_to=utils.uploading.upload_function, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])], verbose_name='Edit preview image')),
            ],
            options={
                'verbose_name': 'Comic book',
                'verbose_name_plural': 'Comics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('is_anonym', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=512)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name="Comment' date")),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.uploading.upload_comics_images, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])])),
                ('comics_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comics', verbose_name='Comics id')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
