# Generated by Django 4.0.2 on 2022-03-09 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='from_comics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comics'),
        ),
        migrations.AddField(
            model_name='comics',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='comics',
            name='unique_views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='comics.IP'),
        ),
    ]
