# Generated by Django 3.2.9 on 2021-11-22 09:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='preview_image',
            field=models.ImageField(upload_to=utils.uploading.upload_function, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])], verbose_name='Edit preview image'),
        ),
        migrations.CreateModel(
            name='LikesDislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Likes and dislikes',
                'verbose_name_plural': 'Likes and dislikes',
            },
        ),
    ]
