# Generated by Django 3.2.9 on 2021-12-07 14:15

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Comics url'),
        ),
        migrations.AlterField(
            model_name='likesdislikes',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Liked'), (0, 'Not liked')], verbose_name='Vote'),
        ),
    ]
