# Generated by Django 3.2.9 on 2021-11-17 07:37

import django.core.validators
from django.db import migrations, models
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('users_profiles', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.uploading.upload_user_avatars_func, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])]),
        ),
    ]
